_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [2]:
#Code here
import numpy as np

a = np.array([10, 5, 7, 20, 15, -9, 33])
print("array:", a)
print("maximum:", a.max())
print("minimum:", a.min())

array: [10  5  7 20 15 -9 33]
maximum: 33
minimum: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [3]:
#Code here
a = [10, 5, 7, 20, 15, -9, 33]

max_val = a[0]
for n in a:
    if n > max_val:
        max_val = n

print("maximum value:", max_val)

maximum value: 33


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [4]:
#Code here
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 4], [6, 8]])

sum = a + b
sub = a - b

print("sum:\n", sum)
print("subtraction:\n", sub)

sum:
 [[ 3  6]
 [ 9 12]]
subtraction:
 [[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [5]:
#Code here
import numpy as np

matrix = np.random.randint(1, 100, size=(5, 6))
print("original matrix:\n", matrix)
row = np.random.randint(1, 100, size=(1, 6))
matrix = np.vstack([matrix, row])
print("matrix with new row:\n", matrix)
row_sums = matrix.sum(axis=1)
print("row sums:", row_sums)

original matrix:
 [[67 52 66 23 18 97]
 [31 10 75 49 94 38]
 [34  3 62 58 70 89]
 [79 90 32 78 17 95]
 [29  3 37 55 56 99]]
matrix with new row:
 [[67 52 66 23 18 97]
 [31 10 75 49 94 38]
 [34  3 62 58 70 89]
 [79 90 32 78 17 95]
 [29  3 37 55 56 99]
 [15 93 13 79 63 14]]
row sums: [323 297 316 391 279 277]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [6]:
#Code here
import numpy as np
matrix = np.random.randint(1, 100, size=(5, 6))
print("original matrix:\n", matrix)
col = np.random.randint(1, 100, size=(5, 1))
matrix = np.hstack([matrix, col])
print("matrix with new column:\n", matrix)
sine_matrix = np.sin(matrix)
print("dine of each element:\n", sine_matrix)

original matrix:
 [[61 75 68 10  1 37]
 [ 1  2 60 92 84 21]
 [36 73 89 36 70 81]
 [99 58  7 10 96 12]
 [34 63 84 98  7 59]]
matrix with new column:
 [[61 75 68 10  1 37 10]
 [ 1  2 60 92 84 21 94]
 [36 73 89 36 70 81 72]
 [99 58  7 10 96 12 49]
 [34 63 84 98  7 59 21]]
dine of each element:
 [[-0.96611777 -0.38778164 -0.89792768 -0.54402111  0.84147098 -0.64353813
  -0.54402111]
 [ 0.84147098  0.90929743 -0.30481062 -0.77946607  0.73319032  0.83665564
  -0.24525199]
 [-0.99177885 -0.67677196  0.86006941 -0.99177885  0.77389068 -0.62988799
   0.25382336]
 [-0.99920683  0.99287265  0.6569866  -0.54402111  0.98358775 -0.53657292
  -0.95375265]
 [ 0.52908269  0.1673557   0.73319032 -0.57338187  0.6569866   0.63673801
   0.83665564]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [7]:
#Code here
import numpy as np

matrix = np.random.randint(1, 100, size=(5, 6))
print("original matrix:\n", matrix)
sliced_matrix = matrix[2:4, 1:4]
print("sliced matrix (rows 3-4, cols 2-4):\n", sliced_matrix)

original matrix:
 [[12 70 22  1  7 84]
 [53  2 90 29 99 23]
 [83 67 94 82 34 93]
 [76 44 10 77 66 42]
 [39 28 36 78  3 84]]
sliced matrix (rows 3-4, cols 2-4):
 [[67 94 82]
 [44 10 77]]


### Great Job!